# This code was generated by Claude
"""
Perceptual palette quantizer: drop-in upgrade for quantize_most_frequent_sk.

Pipeline
  1. Collapse the image to its unique RGBA colors + pixel counts (fast, and makes
     everything frequency-weighted for free).
  2. Convert to Oklab so distances approximate perceived difference.
  3. Seed a palette with weighted median-cut (splits the box with the largest
     weighted squared error), then refine with a few weighted Lloyd iterations.
     If the image has <= n_colors unique colors the palette is exact (lossless).
  4. Optionally order the palette for index locality (helps RLE / delta coding).
  5. Map pixels with a KD-tree in Oklab, with optional dithering:
       - "ordered": Bayer matrix, fully vectorised, run-friendly
       - "fs":      serpentine Floyd-Steinberg in Oklab with error clamping
"""
import heapq

import numpy as np
from PIL import Image
from scipy.spatial import cKDTree

# ---------------------------------------------------------------- Oklab ----
_M1 = np.array([[0.4122214708, 0.5363325363, 0.0514459929],
                [0.2119034982, 0.6806995451, 0.1073969566],
                [0.0883024619, 0.2817188376, 0.6299787005]])
_M2 = np.array([[0.2104542553, 0.7936177850, -0.0040720468],
                [1.9779984951, -2.4285922050, 0.4505937099],
                [0.0259040371, 0.7827717662, -0.8086757660]])
_M1_INV = np.linalg.inv(_M1)
_M2_INV = np.linalg.inv(_M2)


def _srgb_to_oklab(rgb_u8):
    c = rgb_u8.astype(np.float64) / 255.0
    lin = np.where(c <= 0.04045, c / 12.92, ((c + 0.055) / 1.055) ** 2.4)
    lms = np.cbrt(lin @ _M1.T)
    return lms @ _M2.T


def _oklab_to_srgb(lab):
    lms = (lab @ _M2_INV.T) ** 3
    lin = np.clip(lms @ _M1_INV.T, 0.0, 1.0)
    c = np.where(lin <= 0.0031308, lin * 12.92, 1.055 * lin ** (1 / 2.4) - 0.055)
    return np.clip(np.rint(c * 255.0), 0, 255).astype(np.uint8)


def _to_features(rgba, wvec):
    """RGBA uint8 (N,4) -> weighted [L, a, b, alpha] float64 (N,4)."""
    lab = _srgb_to_oklab(rgba[:, :3])
    lab[rgba[:, 3] == 0] = 0.0  # colour of fully transparent pixels is meaningless
    feat = np.empty((len(rgba), 4), dtype=np.float64)
    feat[:, :3] = lab
    feat[:, 3] = rgba[:, 3] / 255.0
    return feat * wvec


def _from_features(feat, wvec):
    f = feat / wvec
    rgba = np.empty((len(f), 4), dtype=np.uint8)
    rgba[:, :3] = _oklab_to_srgb(f[:, :3])
    rgba[:, 3] = np.clip(np.rint(f[:, 3] * 255.0), 0, 255).astype(np.uint8)
    return rgba


# ------------------------------------------------------ palette building ----
def _median_cut(pts, w, k):
    """Weighted median cut; always splits the box with the largest SSE."""
    def stats(idx):
        bw, bp = w[idx], pts[idx]
        mean = (bp * bw[:, None]).sum(0) / bw.sum()
        return (((bp - mean) ** 2) * bw[:, None]).sum(0)

    heap, done, n = [], [], 0
    root = np.arange(len(pts))
    var = stats(root)
    heapq.heappush(heap, (-var.sum(), n, root, var))
    while heap and len(heap) + len(done) < k:
        _, _, idx, var = heapq.heappop(heap)
        if len(idx) < 2:
            done.append(idx)
            continue
        axis = int(np.argmax(var))
        order = idx[np.argsort(pts[idx, axis], kind="stable")]
        cw = np.cumsum(w[order])
        s = int(np.searchsorted(cw, cw[-1] / 2)) + 1
        s = min(max(s, 1), len(order) - 1)
        for part in (order[:s], order[s:]):
            n += 1
            v = stats(part)
            heapq.heappush(heap, (-v.sum(), n, part, v))
    boxes = [h[2] for h in heap] + done
    return np.stack([(pts[b] * w[b, None]).sum(0) / w[b].sum() for b in boxes])


def _lloyd(pts, w, centers, iters):
    k = len(centers)
    for _ in range(iters):
        _, lab = cKDTree(centers).query(pts, workers=-1)
        ws = np.bincount(lab, weights=w, minlength=k)
        new = np.stack([np.bincount(lab, weights=w * pts[:, d], minlength=k)
                        for d in range(pts.shape[1])], axis=1)
        m = ws > 0
        centers[m] = new[m] / ws[m, None]
    return centers


def _locality_order(feat):
    """Order palette so neighbouring indices are perceptually close:
    lightness bands, then hue sweeps alternating direction per band."""
    n = len(feat)
    bands = max(1, int(np.sqrt(n) / 2))
    rank = np.empty(n, dtype=np.int64)
    rank[np.argsort(feat[:, 0], kind="stable")] = np.arange(n)
    band = rank * bands // n
    hue = np.arctan2(feat[:, 2], feat[:, 1])
    hue = np.where(band % 2 == 0, hue, -hue)
    return np.lexsort((hue, band))


# --------------------------------------------------------------- dithering --
def _bayer(n):
    m = np.array([[0]])
    while m.shape[0] < n:
        m = np.block([[4 * m, 4 * m + 2], [4 * m + 3, 4 * m + 1]])
    return (m + 0.5) / (n * n) - 0.5  # centred on 0, range (-0.5, 0.5)


def _palette_spacing(pal_feat):
    """Median nearest-neighbour distance between palette entries (colour axes)."""
    if len(pal_feat) < 2:
        return 0.0
    d, _ = cKDTree(pal_feat[:, :3]).query(pal_feat[:, :3], k=2)
    return float(np.median(d[:, 1]))


# --------------------------------------------------------------- public API --
def quantize_perceptual(img: Image.Image, n_colors: int, palette: list = None,
                        dither: bool = False, *, dither_mode: str = "ordered",
                        dither_strength: float = 0.8, kmeans_iters: int = 6,
                        lightness_weight: float = 1.0, alpha_weight: float = 1.0,
                        sort_palette: bool = True):
    """Returns (RGBA PIL image, palette as list of (r,g,b,a) tuples).

    palette          fixed palette; skips palette generation (and sorting)
    dither_mode      "ordered" (Bayer, run-friendly) or "fs" (Floyd-Steinberg)
    dither_strength  0..1+, scales the dither amplitude / diffused error
    lightness_weight >1 spends more palette on luminance detail
    alpha_weight     how much alpha differences count versus colour
    """
    img = img.convert("RGBA")
    arr = np.ascontiguousarray(np.array(img, dtype=np.uint8))
    h, w = arr.shape[:2]
    flat = arr.reshape(-1, 4)
    wvec = np.array([lightness_weight, 1.0, 1.0, alpha_weight])

    # unique colours + counts
    packed = flat.view(np.uint32).ravel()
    uniq, inv, counts = np.unique(packed, return_inverse=True, return_counts=True)
    inv = inv.ravel()
    uniq_rgba = np.ascontiguousarray(uniq).view(np.uint8).reshape(-1, 4)
    uniq_feat = _to_features(uniq_rgba, wvec)

    # palette
    if palette is not None:
        pal_rgba = np.array(palette, dtype=np.uint8)
        if pal_rgba.shape[1] == 3:
            pal_rgba = np.concatenate(
                [pal_rgba, np.full((len(pal_rgba), 1), 255, np.uint8)], axis=1)
    elif len(uniq_rgba) <= n_colors:
        pal_rgba = uniq_rgba.copy()
    else:
        cnt = counts.astype(np.float64)
        centers = _median_cut(uniq_feat, cnt, n_colors)
        centers = _lloyd(uniq_feat, cnt, centers, kmeans_iters)
        pal_rgba = _from_features(centers, wvec)
    pal_feat = _to_features(pal_rgba, wvec)  # use the *actual* 8-bit palette
    if palette is None and sort_palette:
        order = _locality_order(pal_feat)
        pal_rgba, pal_feat = pal_rgba[order], pal_feat[order]

    tree = cKDTree(pal_feat)
    _, base_u = tree.query(uniq_feat, workers=-1)
    base_idx = base_u[inv]  # plain nearest-colour index per pixel

    if not dither or len(pal_rgba) < 2:
        idx = base_idx
    else:
        spacing = _palette_spacing(pal_feat)
        feat_all = uniq_feat[inv]  # (N,4)
        opaque = flat[:, 3] > 0

        if dither_mode == "ordered":
            tile = _bayer(8)
            thr = np.tile(tile, (h // 8 + 1, w // 8 + 1))[:h, :w].reshape(-1)
            shifted = feat_all.copy()
            # thr spans (-0.5, 0.5); nearest-neighbour spacing underestimates the
            # real cell width in a sparse 3D palette, so scale by 2 (+/- 1 step at 1.0)
            shifted[:, :3] += (thr * 2.0 * spacing * dither_strength)[:, None]
            _, idx = tree.query(shifted, workers=-1)
            idx = np.where(opaque, idx, base_idx)

        elif dither_mode == "fs":
            buf = feat_all.reshape(h, w, 4).copy()
            opq = opaque.reshape(h, w)
            base2d = base_idx.reshape(h, w)
            out = np.empty((h, w), dtype=np.int64)
            lim = spacing  # clamp so error cannot snowball past one palette step
            for y in range(h):
                ltr = (y % 2 == 0)
                xs = range(w) if ltr else range(w - 1, -1, -1)
                dx = 1 if ltr else -1
                for x in xs:
                    if not opq[y, x]:
                        out[y, x] = base2d[y, x]
                        continue
                    old = buf[y, x]
                    _, i = tree.query(old)
                    out[y, x] = i
                    err = np.clip(old[:3] - pal_feat[i, :3], -lim, lim) * dither_strength
                    xn = x + dx
                    if 0 <= xn < w:
                        buf[y, xn, :3] += err * (7 / 16)
                    if y + 1 < h:
                        xb = x - dx
                        if 0 <= xb < w:
                            buf[y + 1, xb, :3] += err * (3 / 16)
                        buf[y + 1, x, :3] += err * (5 / 16)
                        if 0 <= xn < w:
                            buf[y + 1, xn, :3] += err * (1 / 16)
            idx = out.reshape(-1)
        else:
            raise ValueError("dither_mode must be 'ordered' or 'fs'")

    quantized = pal_rgba[idx].reshape(h, w, 4)
    return Image.fromarray(quantized, "RGBA"), [tuple(int(v) for v in c) for c in pal_rgba]